spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/fitmatch}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.fitmatch: INFO
    org.hibernate.SQL: WARN
