-- =====================================================================
-- V52 (UC-075): template thông báo admin chỉnh được. Mỗi code khớp một sự
-- kiện trong NotificationDispatcher; nội dung seed = văn bản mặc định hiện
-- hành trong code (placeholder {key} thay lúc gửi). Tắt/thiếu template ->
-- dùng mặc định trong code. API chỉ cho UPDATE — không tạo code mới.
-- =====================================================================

create table notification_templates (
    id bigint not null auto_increment,
    code varchar(60) not null,
    title varchar(200) not null,
    body varchar(1000) not null,
    enabled tinyint(1) not null default 1,
    placeholders varchar(255) null,
    created_at datetime(6) not null,
    updated_at datetime(6),
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id),
    unique key uk_notification_templates_code (code)
) engine = InnoDB;

insert into notification_templates (code, title, body, placeholders, created_at) values
('BOOKING_CANCELLED_BY_CUSTOMER_GYM', 'Khách hủy lịch đặt',
 'Khách đã hủy booking #{bookingId}. {reason}', '{bookingId}, {reason}', utc_timestamp()),
('BOOKING_CANCELLED_BY_CUSTOMER_PT', 'Buổi tập bị khách hủy',
 'Khách đã hủy booking #{bookingId}. {reason}', '{bookingId}, {reason}', utc_timestamp()),
('WITHDRAWAL_DECIDED', 'Yêu cầu rút tiền #{withdrawalId} {decision}',
 '{detail}', '{withdrawalId}, {decision}, {detail}', utc_timestamp()),
('WAITLIST_SLOT_OPENED', 'Đã có chỗ trống',
 'Khung giờ cho "{itemName}" vừa trống ra — đặt ngay trước khi hết chỗ.', '{itemName}', utc_timestamp()),
('BOOKING_ROUTED_TO_GYM', 'Yêu cầu đặt lịch mới',
 'Booking #{bookingId} đang chờ bạn xác nhận.', '{bookingId}', utc_timestamp()),
('BOOKING_ACCEPTED_CUSTOMER', 'Lịch đặt đã được xác nhận',
 'Booking #{bookingId} đã được phòng gym xác nhận.', '{bookingId}', utc_timestamp()),
('BOOKING_ASSIGNED_PT', 'Bạn được phân công buổi tập',
 'Booking #{bookingId} đã được gán cho bạn.', '{bookingId}', utc_timestamp()),
('BOOKING_PT_UPDATED_CUSTOMER', 'Huấn luyện viên được cập nhật',
 'Booking #{bookingId} đã được cập nhật huấn luyện viên phụ trách.', '{bookingId}', utc_timestamp()),
('BOOKING_REJECTED_CUSTOMER', 'Lịch đặt bị từ chối',
 'Booking #{bookingId} bị từ chối: {reason}. Tiền (nếu có) sẽ được hoàn.', '{bookingId}, {reason}', utc_timestamp()),
('BOOKING_CANCELLED_BY_GYM_CUSTOMER', 'Lịch đặt bị hủy',
 'Booking #{bookingId} bị phòng gym hủy: {reason}.', '{bookingId}, {reason}', utc_timestamp()),
('BOOKING_COMPLETED_CUSTOMER', 'Buổi tập hoàn tất',
 'Booking #{bookingId} đã hoàn tất. Bạn có thể đánh giá buổi tập.', '{bookingId}', utc_timestamp()),
('BOOKING_NO_SHOW_CUSTOMER', 'Ghi nhận vắng mặt',
 'Booking #{bookingId} được ghi nhận là vắng mặt.', '{bookingId}', utc_timestamp()),
('PT_SUSPENDED_GYM', 'PT bị đình chỉ — cần xử lý booking',
 'PT của booking #{bookingId} đã bị đình chỉ. {reason} Vui lòng phân công PT khác hoặc hủy buổi này.',
 '{bookingId}, {reason}', utc_timestamp()),
('PT_SUSPENDED_CUSTOMER', 'Buổi tập cần được sắp xếp lại',
 'PT của booking #{bookingId} tạm thời không thể phục vụ. Phòng gym sẽ liên hệ để sắp xếp lại.',
 '{bookingId}', utc_timestamp()),
('GYM_VERIFICATION_DECIDED', 'Kết quả duyệt hồ sơ phòng gym',
 'Hồ sơ phòng gym của bạn: {decision}. {note}', '{decision}, {note}', utc_timestamp()),
('PAYMENT_HELD_CUSTOMER', 'Thanh toán thành công',
 'Đã nhận thanh toán cho booking #{bookingId}.', '{bookingId}', utc_timestamp()),
('PAYMENT_EXPIRED_CUSTOMER', 'Hết hạn thanh toán',
 'Booking #{bookingId} đã bị hủy vì quá hạn thanh toán. Điểm/voucher đã dùng (nếu có) được hoàn lại — bạn có thể đặt lịch mới.',
 '{bookingId}', utc_timestamp()),
('PAYMENT_FAILED_CUSTOMER', 'Thanh toán thất bại',
 'Thanh toán cho booking #{bookingId} chưa được ghi nhận: {reason}. Vui lòng liên hệ hỗ trợ nếu bạn đã chuyển khoản.',
 '{bookingId}, {reason}', utc_timestamp()),
('REFUND_EXECUTED_CUSTOMER', 'Hoàn tiền đã thực hiện',
 'Đã hoàn {amount} cho booking #{bookingId}.', '{bookingId}, {amount}', utc_timestamp()),
('SETTLEMENT_RELEASED_GYM', 'Tiền đã về ví khả dụng',
 'Booking #{bookingId}: {amount} đã sẵn sàng để rút.', '{bookingId}, {amount}', utc_timestamp()),
('DISPUTE_OPENED_PARTY', 'Tranh chấp mới',
 'Tranh chấp #{disputeId} liên quan booking #{bookingId} vừa được mở.', '{disputeId}, {bookingId}', utc_timestamp()),
('DISPUTE_RESOLVED_PARTY', 'Tranh chấp đã được giải quyết',
 'Tranh chấp #{disputeId} kết luận: {resolution}.', '{disputeId}, {resolution}', utc_timestamp()),
('REVIEW_REPLIED_CUSTOMER', 'Phòng gym đã phản hồi đánh giá',
 'Đánh giá của bạn cho {gymName} đã được phản hồi.', '{gymName}', utc_timestamp()),
('REVIEW_MODERATED_CUSTOMER', 'Đánh giá của bạn được kiểm duyệt',
 'Đánh giá của bạn đã chuyển trạng thái {status}.', '{status}', utc_timestamp());
